// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiqwcZgRvNBq3liSY7fHYnfEIgXLSkEys',
    appId: '1:170302508520:web:f6a229ce2c7e368bbd285d',
    messagingSenderId: '170302508520',
    projectId: 'jalrakshak-f1d6a',
    authDomain: 'jalrakshak-f1d6a.firebaseapp.com',
    storageBucket: 'jalrakshak-f1d6a.firebasestorage.app',
    measurementId: 'G-LY5SLJLZT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApSJhVwnnMUt0G6OD-5N94IfYn_uxyYdA',
    appId: '1:170302508520:android:9e3ff9f6e3927ceabd285d',
    messagingSenderId: '170302508520',
    projectId: 'jalrakshak-f1d6a',
    storageBucket: 'jalrakshak-f1d6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAocTBghzpw8SAkK6MRyv3mR83YwI42QtI',
    appId: '1:170302508520:ios:432dd515ecd7ef35bd285d',
    messagingSenderId: '170302508520',
    projectId: 'jalrakshak-f1d6a',
    storageBucket: 'jalrakshak-f1d6a.firebasestorage.app',
    iosClientId: '170302508520-l67f9rh2armc3dmg9smbh5rnqhmvmqsh.apps.googleusercontent.com',
    iosBundleId: 'com.example.janrakshak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAocTBghzpw8SAkK6MRyv3mR83YwI42QtI',
    appId: '1:170302508520:ios:432dd515ecd7ef35bd285d',
    messagingSenderId: '170302508520',
    projectId: 'jalrakshak-f1d6a',
    storageBucket: 'jalrakshak-f1d6a.firebasestorage.app',
    iosClientId: '170302508520-l67f9rh2armc3dmg9smbh5rnqhmvmqsh.apps.googleusercontent.com',
    iosBundleId: 'com.example.janrakshak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiqwcZgRvNBq3liSY7fHYnfEIgXLSkEys',
    appId: '1:170302508520:web:67342dff0141850cbd285d',
    messagingSenderId: '170302508520',
    projectId: 'jalrakshak-f1d6a',
    authDomain: 'jalrakshak-f1d6a.firebaseapp.com',
    storageBucket: 'jalrakshak-f1d6a.firebasestorage.app',
    measurementId: 'G-31RSV6BT11',
  );
}
